# -*- coding: utf-8 -*-
"""
Multi-scenario UAV 3D path planning (manuscript Section "Multi-Scenario UAV 3D
Path Planning").

Three terrain scenarios are modelled (mountain, urban, maritime). A smooth 3D
path is generated by fitting a Catmull--Rom spline through 6 control points
(x, y, z each -> 18 optimisation variables, matching the manuscript). The cost
function combines path length, collision penalty and turning smoothness with
time-varying adaptive weights:

    J = w1(t)*L_path + w2(t)*C_collision + w3*S_smooth
    w1 = 0.6 - 0.2 t/Tmax,  w2 = 0.2 + 0.2 t/Tmax,  w3 = 0.2

A hard turning-angle constraint theta_j <= theta_max (45 deg) is checked at the
final-selection stage (kinematic feasibility). The cruise speed v_c = 30 m/s
enters the traversal-time computation for reference.

Reproduction note: this is a faithful, self-contained re-implementation of the
planning model described in the manuscript (same terrain equations, control
points, cost weights and protocol). Reported metrics are freshly generated by
this code and may differ from the manuscript's published numbers.
"""
from __future__ import annotations

import numpy as np


# ---------------------------------------------------------------------------
# Terrain scenarios (analytic, vectorised over x, y arrays)
# ---------------------------------------------------------------------------
def terrain_mountain(x, y):
    z1 = 10.0 * np.exp(-((x - 30.0) ** 2 + (y - 30.0) ** 2) / 800.0)
    z2 = 15.0 * np.exp(-((x - 70.0) ** 2 + (y - 70.0) ** 2) / 1000.0)
    return np.maximum(z1, z2)


def terrain_urban(x, y):
    z = np.zeros_like(x)
    buildings = [(30.0, 30.0, 35.0), (30.0, 70.0, 35.0),
                 (70.0, 30.0, 35.0), (70.0, 70.0, 35.0), (50.0, 50.0, 25.0)]
    half = 10.0  # building half footprint
    for cx, cy, h in buildings:
        inside = (np.abs(x - cx) <= half) & (np.abs(y - cy) <= half)
        z = np.where(inside, h, z)
    return z


def terrain_maritime(x, y):
    z = 2.0 * np.sin(0.05 * x) * np.cos(0.05 * y)
    islands = [(20.0, 20.0, 12.0), (80.0, 30.0, 15.0),
               (50.0, 80.0, 10.0), (90.0, 90.0, 8.0)]
    for ix, iy, h in islands:
        z = z + h * np.exp(-((x - ix) ** 2 + (y - iy) ** 2) / 200.0)
    return z


SCENARIOS = {
    "Mountain": terrain_mountain,
    "Urban": terrain_urban,
    "Maritime": terrain_maritime,
}

START = np.array([0.0, 0.0], dtype=float)
TARGET = np.array([100.0, 100.0], dtype=float)
SAFETY = 10.0           # required clearance above terrain (m)
THETA_MAX = np.deg2rad(45.0)
V_CRUISE = 30.0         # m/s


# ---------------------------------------------------------------------------
# Catmull-Rom spline through control points (smooth, C1)
# ---------------------------------------------------------------------------
def _catmull_rom_matrix(n_control, samples_per_segment=40):
    """Return (S, n_control) coefficient matrix mapping control points to a
    dense smooth path through them (Catmull-Rom, clamped at the ends)."""
    n_seg = n_control - 1
    S = n_seg * samples_per_segment
    C = np.zeros((S, n_control))
    for i in range(n_seg):
        for k in range(samples_per_segment):
            s = k / samples_per_segment
            row = i * samples_per_segment + k
            p0 = max(i - 1, 0)
            p3 = min(i + 2, n_control - 1)
            C[row, p0] += 0.5 * (-s + 2.0 * s ** 2 - s ** 3)
            C[row, i] += 0.5 * (2.0 - 5.0 * s ** 2 + 3.0 * s ** 3)
            C[row, i + 1] += 0.5 * (s + 4.0 * s ** 2 - 3.0 * s ** 3)
            C[row, p3] += 0.5 * (-s ** 2 + s ** 3)
    return C


class UAVPlanner:
    """Terrain-aware path planner using the PCA-PIO / baseline optimisers."""

    def __init__(self, scenario, n_control=6, samples_per_segment=40,
                 safety=SAFETY, theta_max=THETA_MAX, anchor_w=0.5):
        self.scenario = scenario
        self.terrain = SCENARIOS[scenario]
        self.n_control = n_control
        self.C = _catmull_rom_matrix(n_control, samples_per_segment)
        self.samples_per_segment = samples_per_segment
        self.safety = safety
        self.theta_max = theta_max
        self.anchor_w = anchor_w
        # optimisation bounds: each control point is (x, y, z)
        self.lo = np.tile(np.array([0.0, 0.0, 5.0]), n_control)
        self.hi = np.tile(np.array([100.0, 100.0, 80.0]), n_control)
        self.dim = n_control * 3
        # fixed start / target anchors
        self.z_start = float(self.terrain(START[0], START[1])) + safety
        self.z_target = float(self.terrain(TARGET[0], TARGET[1])) + safety

    # -- path construction -------------------------------------------------
    def path_from_control(self, cp):
        cp = np.asarray(cp, dtype=float).reshape(self.n_control, 3)
        return self.C @ cp  # (S, 3)

    # -- evaluation ---------------------------------------------------------
    def evaluate(self, cp, t, Tmax):
        """Return (cost, metrics) for control points at iteration t.

        metrics: dict with path_length, turning_angle, collisions, success.
        """
        path = self.path_from_control(cp)
        x, y, z = path[:, 0], path[:, 1], path[:, 2]
        zt = self.terrain(x, y)

        # path length
        seg = np.sqrt(np.sum(np.diff(path, axis=0) ** 2, axis=1))
        L = float(np.sum(seg))

        # collision penalty (squared clearance violation below safety height)
        clear = z - (zt + self.safety)
        below = clear < 0.0
        C_col = float(np.sum(clear[below] ** 2))

        # turning angles at interior points
        d = np.diff(path, axis=0)                       # (S-1, 3)
        norm = np.linalg.norm(d, axis=1)
        # angle between consecutive chords
        cosang = np.sum(d[1:] * d[:-1], axis=1) / (norm[1:] * norm[:-1] + 1e-12)
        cosang = np.clip(cosang, -1.0, 1.0)
        theta = np.arccos(cosang)                       # radians
        avg_theta = float(np.mean(theta)) if len(theta) else 0.0
        S_smooth = float(np.sum(1.0 - cosang))

        # endpoint anchoring toward fixed start / target
        p0 = cp[0]
        p5 = cp[-1]
        ep = float(np.sum((p0 - np.array([0.0, 0.0, self.z_start])) ** 2)
                   + np.sum((p5 - np.array([100.0, 100.0, self.z_target])) ** 2))

        # adaptive weights (manuscript Eq.)
        w1 = 0.6 - 0.2 * t / Tmax
        w2 = 0.2 + 0.2 * t / Tmax
        w3 = 0.2
        cost = w1 * L + w2 * C_col + w3 * S_smooth + self.anchor_w * ep

        # metrics
        collision = bool(np.any(below)) or bool(np.any(clear < 0.0))
        turning_ok = bool(np.all(theta <= self.theta_max)) if len(theta) else True
        success = (not collision) and turning_ok
        metrics = dict(
            path_length=L,
            turning_angle=np.rad2deg(avg_theta),
            collisions=int(collision),
            success=int(success),
        )
        return cost, metrics

    def cost_function(self, Tmax):
        """Return a callable cost closure for the optimisers (fitness = cost)."""
        def cost(cp):
            c, _ = self.evaluate(cp, t=0, Tmax=Tmax)
            return c
        return cost


def run_uav_planning(scenario, algorithm, seed, N=30, Tmax=200, n_control=6):
    """Run one algorithm on one scenario and return (metrics, best_cost)."""
    from .algorithms import run_with_dim

    planner = UAVPlanner(scenario, n_control=n_control)

    def cost(cp):
        c, _ = planner.evaluate(cp, t=0, Tmax=Tmax)
        return c

    best_fit, best_sol = run_with_dim(
        cost, (planner.lo, planner.hi), planner.dim, seed, algorithm,
        N=N, Tmax=Tmax, T1=int(0.8 * Tmax), return_solution=True)

    _, metrics = planner.evaluate(best_sol, t=Tmax, Tmax=Tmax)
    return metrics, best_fit
